[package]
name = "climacampo"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
bcrypt = "0.17.0"
chrono = "0.4.41"
dotenv = "0.15.0"
futures = "0.3.31"
mongodb = "3.2.4"
serde = { version = "1.0.219", features = ["derive"] }
uuid = "1.17.0"