name: Rust

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Copy file via SSH password
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.PASSWORD }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "."
        target: system
