name: Rust

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

    - name: Checkout
      uses: actions/checkout@v1
    - name: Deploy para hostinger
      uses: easingthemes/ssh-deploy@main
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.KEY_SSH }}
        ARGS: "-rlgoDzvc -i --delete"
        SOURCE: ""
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        REMOTE_PORT: ${{ secrets.PORT }}
        TARGET: system
